### ISSUE TITLE
once a noble man using the professional C++ to be Descending down to rust, the language that nobody asked for. But there is no need to worry as a professional cpp user. I respect your choice, but if you need a quick fix/cure to your tetanus, here you go... you welcome. 

### ISSUE THREAD

**Issue by Legend2525** [WyvernAllow/Rust-Calculator#1]
Method 1: Uninstall Rust with a third-party uninstaller.
1	
DOWNLOAD and install Revo Uninstaller Pro - 30 days fully functional trial version

2	
Start Revo Uninstaller Pro and open the module "Logs Database"

screenshot of logs database
3	
In the Search field type "Rust" and you will see all logs of "Rust" in the database compatible with your Windows Version.

4	
Select the appropriate log by version from the list and press the "Uninstall" button from the toolbar

screenshot of logs uninstall
5	
You will see few popping up windows showing the download and import of the log to your Revo Uninstaller Pro and then the main Uninstall dialog that shows the progress of the uninstall of Rust.

Method 2: Uninstall Rust via Apps and Features/Programs and Features.
1	
Open the Start Menu and type Apps and Features

screenshot of apps and features
2	
Look for Rust in the list and click on it. The next step is to click on uninstall, so you can initiate the uninstallation.

screenshot of apps and features

Method 3: Uninstall Rust with its uninstaller.exe.
Most of the computer programs have uninstall.exe or uninst000.exe in their installation folders. You need to execute these files in order to start the uninstallation process. Here are the steps:

1	
Go to the installation folder of Rust. Most of the times it is located in C:\Programs files or C:\Program files(x86)

2	
Locate uninstall.exe or uninst000.exe

screenshot of uninstall.exe
3	
Double click the file to start the uninstallation process.

Method 4: Uninstall String with Run
1	
Hold the Windows + R keys to open the Run command.

screenshot of run command
2	
 this uninstallation string
"C:\Rust\unins000.exe"

and paste it in the Run command window and click OK.

3	
Follow the instructions to complete the uninstallation

**Comment by Legend2525** [comment]
Banger tip

**Comment by WyvernAllow** [comment]
![image](https://user-images.githubusercontent.com/96000818/232138567-95640263-4ddb-424e-92a4-9bece611e8de.png)

**Comment by Legend2525** [comment]
Listen here little shit

**Comment by Legend2525** [comment]
Attention wants me

**Comment by Legend2525** [comment]
I was offering help, yet you repent
